version: '3'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - news-api
  news-api:
    image: news-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8080:8080'
    environment:
      NEWS_API_BASE_URL: "https://newsapi.org"
      NEWS_API_AUTH_TOKEN: ccaf5d41cc5140c984818c344edcc14d
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - news-api
networks:
  news-api:
    driver: bridge
    name: news-api
volumes:
  redis_data: