version: '3'

services:
  news-api:
    image: news-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8080:8080'
    environment:
      NEWS_API_BASE_URL: "http://mock-news-api:8080"
      NEWS_API_AUTH_TOKEN: test
    networks:
      - news-api

  mock-news-api:
    image: wiremock/wiremock:main-alpine
    ports:
      - '9050:8080'
    networks:
      - news-api

networks:
  news-api:
    driver: bridge
    name: news-api